Module 1: Portfolio mobile version
Fadahunsiseyi/Portfolio-setup-and-mobile-version-skeleton pull request #1
Opened 2022-05-25 21:43 UTC by Fadahunsiseyi

1. Added the index.html
2. Added the styles.css and linked it with index.html
3. Added a background color in place of the background image, because I couldn't find a bg image for my template.

2022-05-25 23:07 UTC, tufoinnkuo10 requested changes
Hi @Fadahunsiseyi 

Great job so far with your progress 😄 . There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Good commit messages
✅ linter checks validated
✅ Good pull request summary
✅ Correct Readme template

Required Changes ♻️
Check the comments under the review

- [ ] please add a `.gitignore` file .  please also ensure that the file has your  `node_modules` inside so you don't accidentally push them to your remote repository

**Optional suggestions**
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-05-25 23:07 UTC, tufoinnkuo10 commented on index.html
> +    </nav>
- [ ] please ensure that the container carrying the tool bar section is a `header tag`.

2022-05-25 23:07 UTC, tufoinnkuo10 commented on index.html
> +        </a>
- [ ] only the hamburger should be inside the nav tag and not the logo.. 
```
<header>
    <p>logo<p/>
   <nav>hamburger<nav/>
<header/>
```

2022-05-25 23:07 UTC, tufoinnkuo10 commented on index.html
> +        <a class="navbar-brand" href="/">Welcome</a>
- [ optional] you can add your name in the place of `welcome` text since you don't have a logo yet

2022-05-25 23:07 UTC, tufoinnkuo10 commented on index.html
> +            <h2>Hey there. I’m Fadahunsi. <br/><span> I’m a software developer</span></h2>
- [ ] please put the first title in an `h1 tag`

2022-05-25 23:07 UTC, tufoinnkuo10 commented on index.html
> +            <a href="/"><img src="./img/twitter.png" alt="The icons" /></a>
- [ ] Add the figma background to your headline section
your design; 👇🏾 
![Screenshot (44)](https://user-images.githubusercontent.com/65298048/170382030-4e67a2f3-6a2c-4a25-a4fd-c13a23eacb86.png)
figma design[ here](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468) 👇🏾 
![Screenshot (42)](https://user-images.githubusercontent.com/65298048/170382087-90e00a5e-cf60-4850-a987-1486fc14769a.png)

2022-05-25 23:07 UTC, tufoinnkuo10 commented on index.html
> +            <a href="/"><img src="./img/twitter.png" alt="The icons" /></a>
- [ ] please put the icons in an `ul tag` and each one in a` li tag` ...
```
<ul>
    <li>icons<li/>
    <li>icons<li/>
<ul/>
```

2022-05-25 23:07 UTC, tufoinnkuo10 commented on style.css
> +  background-image: linear-gradient(to right, rgba(226, 235, 238, 0.62), rgba(195, 206, 200, 0.52));
- [ ]please use the figma background image and not color

2022-05-25 23:07 UTC, tufoinnkuo10 commented on style.css
> +* {
- [ ] please set your bottom margin well. it should look like the original version on figma

2022-05-26 01:39 UTC, Kakalanp requested changes
# STATUS: Changes required :exclamation: 

### Hello there @Fadahunsiseyi! <img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="28px" alt="hi">

### Great work on making the changes requested by a previous reviewer 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. :memo: 

<img src="https://media.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized.gif" alt="almost there">

## Highlights :+1: 
- No linter errors :heavy_check_mark:
- Repo looks professional :briefcase:
- Solid pull request :scroll:

 ## Required Changes ♻️
***Check the comments under the review.***

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 01:39 UTC, Kakalanp commented on index.html
> +    <header class="header">
[OPTIONAL]

Excellent work implementing changes requested by the previous code reviewer! Just to add the cherry on top, you could remove the class and select this element by its `<header>` tag :cherries:

2022-05-26 01:39 UTC, Kakalanp commented on style.css
> +}
Kindly add some padding to this section to make it look more similar to the Figma template :wink:

2022-05-26 08:49 UTC, Kossi-stack approved these changes
## Status: Approved ✔️
**Hi @Fadahunsiseyi ,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 🎉

![](https://user-images.githubusercontent.com/74506933/148243736-d9f63735-4cb1-411f-be28-34972618852d.gif)
You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-05-26 10:16 UTC, merged